query {
  info {
    name
    nouns
    greeting
    role
    headshot {
      fields {
        file {
          url
        }
      }
    }
    skills
    university
    degree
    graduationDate
    contactMessage
    contactEmail
    contactLabel1
    contactLink1
    contactLabel2
    contactLink2
    contactLabel3
    contactLink3
  }
}
